"""One-time authoring helper. Builds original bilingual drafts; no model/API calls."""
import json
from pathlib import Path
root=Path(__file__).resolve().parents[1]
def number(default,lo,hi):return {'type':'number','min':lo,'max':hi,'default':default}
easing={'type':'enum','values':['linear','ease-in','ease-out','ease-in-out'],'default':'ease-out'}
templates={
 'cursor-spotlight':{'radius_px':number(150,40,400),'opacity':number(.25,0,.8),'lift_px':number(6,0,20),'duration_ms':number(240,0,1200)},
 'slide-fade-list':{'duration_ms':number(360,0,2000),'delay_ms':number(70,0,500),'offset_y_px':number(16,-60,60),'easing':easing},
 'hover-lift':{'lift_px':number(6,0,24),'duration_ms':number(240,0,1200)},
 'scale-fade':{'duration_ms':number(320,0,1600),'scale_start':number(.88,.5,1),'easing':easing},
 'skeleton-shimmer':{'duration_ms':number(1400,300,3000)},
 'progress-fill':{'progress':number(65,0,100),'duration_ms':number(700,0,2000),'easing':easing},
 'tab-state':{'duration_ms':number(240,0,1000)},
 'press-feedback':{'scale_start':number(.95,.75,1),'duration_ms':number(140,0,1000)},
 'ripple':{'duration_ms':number(500,0,1400)},
 'ux-state-comparison':{'feedback_delay_ms':number(600,0,1000)},
 'focus-ring':{'offset_px':number(4,0,12)},
 'ux-disclosure':{}, 'ux-error':{}, 'ux-empty':{}, 'ux-validation':{}
}
(root/'previews').mkdir(exist_ok=True)
(root/'previews/registry.json').write_text(json.dumps({'schema_version':1,'templates':{k:{'version':1,'params':v} for k,v in templates.items()}},ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
MDN='https://developer.mozilla.org/en-US/docs/Web/'
rows=[
 ('cursor-spotlight','effect','ui','motion','Cursor Spotlight','鼠标聚光','鼠标跟随,聚光,光晕,高级,悬停','spotlight,glow,cursor,hover,premium','光晕位置跟随指针，用局部亮度变化反馈鼠标所在位置。','A pointer-tracked radial glow makes the hovered region visible.','cursor-spotlight',MDN+'API/Element/pointermove_event','为卡片添加半径 {radius_px}px、透明度 {opacity} 的指针聚光；悬停抬升 {lift_px}px，抬升过渡 {duration_ms}ms。聚光跟随指针且不拦截点击；触摸与减少动态效果时使用静态状态。','Use a pointer-tracked radial glow with radius {radius_px}px and opacity {opacity}. Lift the card by {lift_px}px on hover over {duration_ms}ms. Do not intercept clicks. Use a static state on touch and reduced motion.'),
 ('staggered-reveal','effect','ui','motion','Staggered Reveal','错落入场','依次出现,轻盈,丝滑,列表入场','stagger,sequential,light,smooth,reveal','元素按顺序淡入并位移，帮助用户感知内容的组织关系。','Elements fade and move in sequentially to communicate their organization.','slide-fade-list',MDN+'API/Element/animate','三张卡片从下方 {offset_y_px}px 上移并从透明到不透明，持续 {duration_ms}ms，相邻延迟 {delay_ms}ms，使用 {easing} 缓动。重播前取消未完成动画；减少动态效果时直接显示最终状态。','Fade three cards from transparent to opaque while moving from {offset_y_px}px below the final position over {duration_ms}ms. Stagger by {delay_ms}ms with {easing} easing. Cancel unfinished animations before replay. Show the final state with reduced motion.'),
 ('hover-lift','effect','ui','motion','Hover Lift','悬停抬升','浮起来,悬浮,卡片,轻盈','lift,float,card,light,hover','悬停时向上位移，离开后返回。用于提示可交互性，不改变布局占位。','Lift on hover and return on exit, without changing layout space.','hover-lift',MDN+'CSS/transform','悬停时卡片向上移动 {lift_px}px，离开时回到原位，两次过渡均为 {duration_ms}ms。使用 ease-out，不改变布局。减少动态效果时关闭位移。','Move the card up by {lift_px}px on hover and return on exit. Both transitions last {duration_ms}ms with ease-out, without changing layout. Disable movement for reduced motion.'),
 ('scale-fade','effect','ui','motion','Scale and Fade','缩放淡入','轻轻出现,淡入,弹出,轻盈','scale,fade,appear,light','结合缩放与透明度变化，适合少量新出现的内容。','Combine scale and opacity for a small amount of newly appearing content.','scale-fade',MDN+'API/Element/animate','内容由 {scale_start} 倍缩放与透明状态变为原尺寸与不透明状态，持续 {duration_ms}ms，使用 {easing} 缓动。重播取消旧动画；减少动态效果时直接显示最终状态。','Animate from scale {scale_start} and opacity 0 to scale 1 and opacity 1 over {duration_ms}ms with {easing} easing. Cancel earlier animations on replay. Show the final state for reduced motion.'),
 ('skeleton-shimmer','effect','ui','motion','Skeleton Shimmer','骨架屏扫光','加载占位,骨架,扫光,加载','skeleton,shimmer,loading,placeholder','用接近内容布局的占位形状说明加载状态；扫光只是一种可选修饰。','Content-shaped placeholders communicate loading; shimmer is optional decoration.','skeleton-shimmer',MDN+'CSS/@keyframes','骨架占位使用 {duration_ms}ms 周期的横向扫光。真实内容到达后替换骨架；不要显示虚假的加载进度。减少动态效果时关闭扫光并保留静态占位。','Use a skeleton with a horizontal shimmer cycle of {duration_ms}ms. Replace it when real content arrives. Do not imply fake progress. Disable shimmer but retain static placeholders for reduced motion.'),
 ('progress-fill','effect','ui','motion','Determinate Progress','确定性进度条','进度,进度条,反馈,完成度','progress,feedback,completion','已知工作量时显示真实完成比例。本演示的数值由滑块模拟。','Show a real completion ratio when total work is known. This demo simulates it with a slider.','progress-fill',MDN+'HTML/Element/progress','进度条从 0 过渡到 {progress}%，持续 {duration_ms}ms，使用 {easing} 缓动。实际产品应由真实任务进度更新；减少动态效果时直接显示最终比例。','Animate the progress bar from 0 to {progress}% over {duration_ms}ms with {easing} easing. In production, bind it to actual task progress. Show the final value directly for reduced motion.'),
 ('tab-state','effect','ui','motion','Selected Tab State','选中标签状态','标签,切换,导航,选中','tab,switch,navigation,selected','明确区分当前选项与其他选项，支持键盘选择。此处演示视觉状态切换。','Distinguish the selected option and support keyboard selection; this demo illustrates the visual state change.','tab-state','https://www.w3.org/WAI/ARIA/apg/patterns/tabs/','标签被选择时，在 {duration_ms}ms 内过渡到深色背景与浅色文字。保持一个选中项，提供语义状态与键盘入口；减少动态效果时即时切换。','Transition the selected tab to a dark background and light text over {duration_ms}ms. Keep one selected option and expose its semantic state and keyboard access. Switch instantly for reduced motion.'),
 ('press-feedback','effect','ui','motion','Press Feedback','按压反馈','按下,点击,反馈,按钮','press,click,button,feedback','按下时轻微缩小，松开或取消后归位，确认动作已被接收。','A slight scale-down on press acknowledges input; return on release or cancellation.','press-feedback',MDN+'CSS/:active','按钮按压时缩放到 {scale_start}，过渡 {duration_ms}ms；松开、取消或移出后恢复。支持鼠标与键盘按压；减少动态效果时不缩放。','Scale the button to {scale_start} on press over {duration_ms}ms. Restore on release, cancel, or pointer exit. Support pointer and keyboard input. Disable scaling for reduced motion.'),
 ('click-ripple','effect','ui','motion','Click Ripple','点击涟漪','波纹,涟漪,点击反馈,按钮','ripple,wave,click,button','从点击位置扩散并淡出，提供短暂的输入反馈。','A wave expands and fades from the click point to acknowledge input.','ripple',MDN+'API/PointerEvent','点击时从点击位置播放 {duration_ms}ms 的扩散淡出涟漪，限制在按钮边界。键盘激活从中心播放；减少动态效果时关闭涟漪。','Play a {duration_ms}ms expanding and fading ripple from the click point, clipped to the button. Start at the center for keyboard activation. Disable ripple for reduced motion.'),
 ('save-feedback','ux-pattern','ux','feedback','Save Feedback','保存状态反馈','保存,完成,反馈,留住用户','save,feedback,done,retain','点击后显示处理中，完成后明确告知结果。本演示使用本地计时器，不会保存真实数据。','Show pending and completed states after input. This demo uses a local timer and does not save real data.','ux-state-comparison','https://www.w3.org/WAI/WCAG22/Understanding/status-messages.html','演示保存按钮：点击后进入处理中并禁用重复提交，模拟 {feedback_delay_ms}ms 后展示完成状态，通过状态区域告知结果。真实产品等待服务端成功才显示保存完成。','Demonstrate saving: show a pending state and prevent duplicate submission, then show completion after a simulated {feedback_delay_ms}ms. Announce the result in a status region. In production, show completion only after server confirmation.'),
 ('focus-ring','ux-pattern','ux','accessibility','Visible Focus','可见焦点','键盘,焦点,无障碍,选中','keyboard,focus,accessibility','键盘用户需要知道当前操作位置。焦点轮廓不应仅靠微小色差。','Keyboard users need a visible indication of the current input target.','focus-ring','https://www.w3.org/WAI/WCAG22/Understanding/focus-visible.html','键盘焦点使用 3px 轮廓与 {offset_px}px 外边距，保证控件边界清晰；按 Tab 进入输入框即可检查。','Use a 3px visible focus outline with an offset of {offset_px}px. Press Tab to inspect the input focus.'),
 ('progressive-disclosure','ux-pattern','ux','navigation','Progressive Disclosure','渐进披露','展开,更多,简单,不要复杂','disclosure,more,simple,complex','先显示完成任务所需的主要信息，再允许用户主动展开次要信息。','Show primary task information first and let users reveal secondary detail.','ux-disclosure',MDN+'HTML/Element/details','先显示关键说明，将次要信息放入可展开区，提供明确标签与原生键盘操作，不隐藏完成任务的必要信息。','Show essential information first. Put secondary details in a labeled, keyboard-operable disclosure. Never hide information required to complete the task.'),
 ('error-recovery','ux-pattern','ux','feedback','Error Recovery','错误恢复','失败,重试,留住用户,恢复','error,retry,recover,retain','解释失败并给出恢复入口，尽量保留用户已经输入的内容。','Explain a failure, offer recovery, and preserve the user’s input.','ux-error','https://www.w3.org/WAI/WCAG22/Understanding/error-identification.html','提交失败时保留输入，提供可理解的错误说明与重试操作。演示中的重试只改变本地状态，不发起网络请求。','Preserve input after submission fails. Explain the error and provide a retry action. This demo changes local state only and makes no network request.'),
 ('empty-state','ux-pattern','ux','feedback','Actionable Empty State','可行动的空状态','没有内容,空白,引导,留住用户','empty,blank,guidance,retain','当没有内容时说明原因，并提供与当前任务直接相关的下一步。','Explain why no content is available and offer a next step related to the task.','ux-empty','https://m3.material.io/components','没有内容时显示状态说明与一个主要操作。演示操作添加本地占位条目；不要用无关广告替代空状态。','Show an explanation and one primary action when content is empty. The demo action adds a local placeholder entry. Do not replace the empty state with unrelated promotions.'),
 ('inline-validation','ux-pattern','ux','feedback','Inline Validation','行内校验','表单,错误,校验,验证','form,error,validation','在用户离开输入框或提交后，把明确错误与对应字段关联。','Associate clear validation feedback with the field on blur or submission.','ux-validation','https://www.w3.org/WAI/WCAG22/Understanding/error-identification.html','邮箱字段在离焦时检查格式，错误说明与字段关联，不把空白的初始输入立即标成错误。更正后清除错误。','Validate email format on blur. Associate errors with the field, do not flag an untouched empty field immediately, and clear the error after correction.'),
 ('visual-hierarchy','term','ui','layout','Visual Hierarchy','视觉层级','重点,高级,层次,吸引注意','hierarchy,premium,focus,attention','利用字号、字重、位置和对比安排阅读顺序，突出当前最重要的信息。','Use size, weight, position, and contrast to establish reading order. ',None,'https://m3.material.io/styles/typography/overview','为页面建立清晰阅读顺序：主标题、辅助说明、主要操作分别使用可区分的尺寸与对比；保持一个明确的首要动作。','Establish a reading order with distinguishable heading, supporting text, and primary action styles. Keep one clear primary action.'),
 ('whitespace','term','ui','layout','Whitespace','留白','呼吸感,高级,间距,宽松','whitespace,space,premium,breathing','通过未被内容占用的空间分组与突出信息，而不是简单把所有距离放大。','Use unoccupied space to group and emphasize information, rather than enlarging every gap. ',None,'https://m3.material.io/foundations/layout/understanding-layout/overview','相关内容内部间距小于不同分组间距，避免密集信息；用留白强调阅读顺序，并检查窄屏上的内容连续性。','Keep spacing within groups smaller than spacing between groups. Use whitespace to support reading order, and check content continuity on narrow screens.'),
 ('grid-layout','term','ui','layout','Grid Layout','网格布局','对齐,整齐,排版,网格','grid,alignment,layout,order', '用共享列线与间距统一页面结构，窄屏时重新组织列数。','Align elements using shared columns and gaps, and adapt column count on narrow screens.',None,MDN+'CSS/CSS_grid_layout','用共享网格列线组织卡片与标题，统一间距；窄屏改为单列，避免横向溢出，保持阅读顺序。','Organize headings and cards on shared grid lines with consistent gaps. Use one column on narrow screens, avoid horizontal overflow, and preserve reading order.'),
 ('contrast','term','ui','color','Contrast','对比度','看清楚,清晰,颜色,高级','contrast,legibility,color,clear','背景与前景的差异帮助文字和操作被辨认；颜色也不能是状态的唯一表达。','Differences between foreground and background support legibility; color must not be the only state cue.',None,'https://www.w3.org/WAI/WCAG22/Understanding/contrast-minimum.html','检查文字、背景与交互边界的对比，为状态增加文字或图标辅助。常规正文以 WCAG AA 的 4.5:1 要求为检查目标，实际组合需测量。','Measure foreground/background contrast and supplement state colors with text or icons. Check normal text against the WCAG AA 4.5:1 requirement.'),
 ('easing','term','ui','motion','Easing','缓动曲线','丝滑,柔和,自然,快慢','easing,smooth,natural,speed','缓动决定时间与进度的关系。它改变运动节奏，不等于改变持续时间。','Easing maps elapsed time to animation progress. It changes pacing, not duration.',None,MDN+'CSS/easing-function','入场可考虑 ease-out，让开始较快、结束较慢；退出可考虑 ease-in。结合任务与距离观察效果，不把某条曲线当作高级设计的通用保证。','Consider ease-out for entrances and ease-in for exits. Evaluate the curve in context; no single easing curve guarantees a premium design.'),
 ('affordance','term','ux','usability','Affordance and Signifiers','可供性与意符','能点吗,按钮,怎么用,引导','affordance,signifier,click,button','操作可能性与可感知的提示需要配合：按钮外观、标签与状态应帮助用户理解下一步。','Available actions need perceivable cues: appearance, labels, and states should make the next step understandable.',None,'https://www.w3.org/WAI/ARIA/apg/patterns/button/','为主要操作提供明确的按钮外观与动词标签，让可交互区域有足够尺寸，并保持默认、悬停、焦点、禁用状态一致。','Give primary actions a recognizable button shape and verb label. Use adequately sized targets and consistent default, hover, focus, and disabled states.'),
 ('recognition-over-recall','term','ux','usability','Recognition Rather Than Recall','识别优于回忆','记不住,减少学习,迁移门槛,习惯','recognition,recall,learn,familiar','在当前任务位置展示可识别的选项，减少用户记住术语、路径或前一步信息的负担。','Expose recognizable options where needed, reducing the need to remember terms or paths.',None,'https://www.w3.org/WAI/WCAG22/Understanding/consistent-navigation.html','在使用位置展示清晰标签与候选，保持导航位置和命名一致，不要求用户先记住上一页的信息才能继续。','Show clear labels and options where they are used. Keep navigation placement and naming consistent, and avoid requiring recall of information from previous screens.'),
 ('reduced-motion','term','ux','accessibility','Reduced Motion','减少动态效果','头晕,减少动画,无障碍,静态','reduced,motion,dizzy,accessibility','尊重减少动态效果偏好，用静态状态保留相同信息与操作能力。','Respect reduced-motion preferences and preserve equivalent information and actions in a static state.',None,MDN+'CSS/@media/prefers-reduced-motion','检测 prefers-reduced-motion，关闭非必要位移、循环装饰和指针跟随。保留清晰状态反馈与完整操作能力，不把关闭动画当成隐藏信息。','Respect prefers-reduced-motion by disabling nonessential movement, ambient loops, and pointer tracking. Keep clear status feedback and all actions available.'),
 ('information-architecture','term','ux','navigation','Information Architecture','信息架构','找不到,分类,目录,结构','information,architecture,category,find','用符合用户任务的分组、命名与层级组织内容，让人知道自己在哪里、下一步能去哪里。','Organize content with task-based labels, groups, and hierarchy so users know where they are and where to go.',None,'https://www.w3.org/WAI/WCAG22/Understanding/multiple-ways.html','按用户任务组织内容，提供清晰分类、当前位置与可预测导航；在信息量较大时提供搜索与目录等多种查找方式。','Organize content by user tasks with clear categories, location cues, and predictable navigation. For larger collections, provide multiple ways to find content, such as search and a directory.')
]
out=root/'content/items';out.mkdir(parents=True,exist_ok=True)
for ident,kind,domain,category,canonical,zh,za,ea,zd,ed,template,url,zprompt,eprompt in rows:
 p={k:v['default'] for k,v in templates.get(template,{}).items()}
 locales={}
 for locale,name,aliases,desc,prompt in [('zh-CN',zh,za,zd,zprompt),('en',canonical,ea,ed,eprompt)]:
  locales[locale]={'review_status':'draft','name':name,'aliases':aliases.split(','),'description':desc,'use_when':['用于解释或比较与当前任务相关的设计选择。' if locale=='zh-CN' else 'Use to explain or compare design choices relevant to the current task.'],'avoid_when':['不要将演示参数当作通用行业标准。' if locale=='zh-CN' else 'Do not treat demo parameters as universal standards.'],'prompt_template':prompt}
 item={'schema_version':1,'id':ident,'kind':kind,'domain':domain,'category':category,'status':'draft','canonical_name':canonical,'tags':ea.split(','),'related_ids':[],'locales':locales,'preview':{'template_id':template,'params':p} if template else None,'sources':[{'type':'original','note':'原创概念说明与演示；参数为本项目示例，非标准值。','url':None,'license':'MIT','reuse_permission':'not-applicable'},{'type':'reference','note':'概念或实现参考，未复制外部正文与组件代码。','url':url,'license':'not-applicable','reuse_permission':'not-applicable'}]}
 (out/(ident+'.json')).write_text(json.dumps(item,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print(f'Authored {len(rows)} bilingual draft entries; no model calls.')
